services:
  postgres:
    image: postgres:16-alpine
    container_name: masterbook-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: masterbook
      POSTGRES_USER: masterbook
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - masterbook-postgres-data:/var/lib/postgresql/data

    networks:
      - masterbook-network

networks:
  masterbook-network:
    name: masterbook-network

volumes:
  masterbook-postgres-data:
    name: masterbook-postgres-data